blank_issues_enabled: true
contact_links:
  - name: Question or idea
    url: https://github.com/MiracleInvoker/aistudio-folders/discussions
    about: For usage questions and feature ideas, rather than bug reports.
